name: Deploy FitSeek Backend to Tencent Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # 或使用 private_key 更安全
          port: 22
          script: |
            cd ~/FitSeek-backend
            echo "拉取最新代码"
            git pull origin main
            echo "安装依赖"
            npm install
            echo "重启 Node.js 服务"
            pm2 restart server.js --name fitseek-api